 IFND	MEV3_TEST_S
MEV3_TEST_S SET 1
MEV3_MAIN_S SET 1

*
*
* $VER:mev3.0.s 39.01  © (28/Mar/94) M.J.Edwards
* 
*

	Section Code,Code_C

	include	"mev3_macros.s"

_main:
	push	d0-d7/a0-a6
	move.l	sp,_Initial_SP

	bsr	Open_Libraries

_main_running_loop:
_main_setup:
	bsr	Setup_File
_main_run:
	bsr	Handle_File_Messages
_main_shutown:
	bsr	Shutdown_File

_main_shut_down:
	bsr	Close_Libraries	

	move.l	_Initial_SP,sp
	pop	d0-d7/a0-a6

	rts

Setup_File:
	lea	Shutdown_File,a0
	bsr	_Set_Exit_Jump

; lock public screen
	sub.l	a0,a0
	jsr	LockPublicScreen
	move.l	d0,_My_Screen
;; open screen
;	sub.l	a0,a0
;	lea	File_Screen_TagList,a1
;	jsr	Open_Screen
;	move.l	d0,_My_Screen
; get visual info
	move.l	_My_Screen,a0
	jsr	GetVisualInfo
	move.l	d0,_My_VisualInfo
; create gadgets

	lea	_My_Gadgets,a0
	bsr	CreateContext		; -> d0 = gad(get) pointer

	lea	File_Gadget_List,a0
	bsr	Create_Gadgets_List
;	move.l	d1,File_Gadget_Count

; open window
	sub.l	a0,a0
	lea	File_Window_TagList,a1
	move.l	_My_Screen,File_Window_Screen+4		; write screen pointer into window structure
	move.l	_My_Gadgets,File_Window_Gadgets+4	; write gadget pointer into window structure
	jsr	Open_Window
	move.l	d0,_My_Window
	
	move.l	_My_Window,a0
	sub.l	a1,a1
	move.l	_GadToolsBase,a6
	jsr	_LVOGT_RefreshWindow(a6)

	rts

Shutdown_File:
; close window	
	move.l	_My_Window,a0
	jsr	Close_Window
; close gadgets
	move.l	_My_Gadgets,a0
	jsr	FreeGadgets
; remove visual info
	move.l	_My_VisualInfo,a0
	jsr	RemoveVisualInfo
;; close screen
;	move.l	_My_Screen,a0
;	jsr	Close_Screen
; unlock public screen
	move.l	_My_Screen,a0
	bsr	UnLockPublicScreen

	bsr	_Clear_Exit_Jump
	rts

Handle_File_Messages:
	push	a6/a0
	move.l	_My_Window,a3
	moveq.l	#0,d7
.1
	tst.l	d7
	bne	.handle_end
	move.l	wd_UserPort(a3),a0
	moveq.l	#0,d1
	move.b	$f(a0),d1		; mp_SigBit
	move.l	#$1,d0
	asl.l	d1,d0
	move.l	_SysBase,a6
	jsr	_LVOWait(a6)	
.2
	push	a0
	move.l	wd_UserPort(a3),a0
	move.l	_GadToolsBase,a6
	jsr	_LVOGT_GetIMsg(a6)
	pop	a0
	move.l	d0,a1
	tst.l	d0
	beq.s	.1

	push	a0-a3

	move.l	im_Class(a1),d0

.idcmp_not_known
	pop	a0-a3
	push	a0
	move.l	_GadToolsBase,a6
	jsr	_LVOGT_ReplyIMsg(a6)
	pop	a0

	btst	#7,$BFE001
	beq.s	.handle_end
	bra	.2	
.handle_end
	pop	a6/a0
	rts


;****************************************************
;               Library Opens & Closes
;****************************************************

Open_Libraries:
	lea	Close_Libraries,a0
	move.l	a0,_Routine_To_Shutdown_If_Error+4

	move.l	$4.w,_SysBase

	moveq.l	#0,d0			; version ?? dos
	lea	_DosName,a1
	jsr	Open_Library
	move.l	d0,_DosBase

	moveq.l	#0,d0			; version ?? intuition
	lea	_IntuitionName,a1
	jsr	Open_Library
	move.l	d0,_IntuitionBase

	moveq.l	#0,d0			; version ?? graphics
	lea	_GraphicsName,a1
	jsr	Open_Library
	move.l	d0,_GraphicsBase

	moveq.l	#0,d0			; version ?? gadtools
	lea	_GadToolsName,a1
	jsr	Open_Library
	move.l	d0,_GadToolsBase

	moveq.l	#0,d0			; version ?? diskfont
	lea	_DiskFontName,a1
	jsr	Open_Library
	move.l	d0,_DiskFontBase

;	lea	_DPaint50,a0
;	jsr	Open_DiskFont
;	move.l	d0,_DPaintFont
	rts

Close_Libraries:
;	move.l	_DPaintFont,a1
;	jsr	Close_Font
	
	move.l	_DiskFontBase,a1
	jsr	Close_Library

	move.l	_GadToolsBase,a1
	jsr	Close_Library

	move.l	_GraphicsBase,a1
	jsr	Close_Library

	move.l	_IntuitionBase,a1
	jsr	Close_Library

	move.l	_DosBase,a1
	jsr	Close_Library

	move.l	#0,_Routine_To_Shutdown_If_Error+4

	rts

;********************************************
; GadTool Gadget Creation Deletion Functions
;********************************************

Create_Gadgets_List:	; a0 - list of newgadgets (gadtools)
	push	d2-d3/a0
	clr.l	d1		; gadget created counter
.more_gadgets
	tst.l	(a0)		; test for end of GT_gad list
	bmi.s	.no_more_gadgets
	clr.l	d2
	move.w	(a0)+,d2
	move.l	(a0)+,d3
	move.l	_My_VisualInfo,gng_VisualInfo(a0) ; do this for every NewGadget Structure before Creating it
	move.l	#_System80,gng_TextAttr(a0)
	push	d3			; tags
	push	a0			; NewGadget struct
	push	d0			; gad from createcontext
	push	d2			; type -> BUTTON_KIND etc.
	bsr	CreateGadget
	addq.l	#1,d1			; inc created counter
	lea	4*4(sp),sp
	add.l	#gng_SIZEOF,a0
.more_tags
	bra.s	.more_gadgets
.no_more_gadgets
	pop	d2-d3/a0
	rts

CreateContext:		; a0 - pointer to gad pointer
	push	a6
	move.l	_GadToolsBase,a6
	jsr	_LVOCreateContext(a6)
	pop	a6
	rts

CreateGadget:	; sp - Type - Gad - NewGadget - Tags
	push	a0-a2/a6
	lea	5*4(sp),a2
	movem.l	(a2)+,d0/a0-a1
	move.l	(a2),a2
	move.l	_GadToolsBase,a6
	jsr	_LVOCreateGadgetA(a6)
	pop	a0-a2/a6
	rts

FreeGadgets:	; a0 - gadget list generated by create context/gadgets
	push	a6
	move.l	_GadToolsBase,a6
	jsr	_LVOFreeGadgets(a6)
	pop	a6
	rts



	include	"/matts_easystart.s"
	include "/matts_funcs.s"

	INSTALL_Library_Funcs
	INSTALL_Font_Funcs
	INSTALL_DiskFont_Funcs
	INSTALL_ScreenLock_Funcs
;	INSTALL_Screen_Funcs	TagList
	INSTALL_Window_Funcs	TagList
	INSTALL_Visual_Funcs

;	include	"mev3_file.s"
;	include	"mev3_gadget.s"
;	include	"mev3_none.s"
;	include	"mev3_utility_B.s"


_SysBase:		DC.L	0
_DosBase:		DC.L	0
_IntuitionBase:		DC.L	0
_GraphicsBase:		DC.L	0
_GadToolsBase:		DC.L	0
_AslBase:		DC.L	0
_DiskFontBase:		DC.L	0

_File_Handle:		DC.L	0

_SystemFont:		DC.L	0
_DPaintFont:		DC.L	0
_My_VisualInfo:		DC.L	0

_My_Screen:		DC.L	0
_My_Window:		DC.L	0
_My_UserPort:		DC.L	0
_My_RastPort:		DC.L	0
_My_ViewPort:		DC.L	0
_My_Gadgets:		DC.L	0

_Global_RastPort:	DC.L	0


 EVEN

_Message:		DS.L	im_SIZEOF/4
_Quit:			DC.W	0

Minus_1:		DC.L	-1

_System80:		DC.L	_SystemName,$00080000
_DPaint50:		DC.L	_DpaintName,$00050002

 EVEN

Text_Mev3_Title:	DC.B	"Mev3.0",0,0,0

Text_Mev3_Confirm:	DC.B	"Mev3.0 : Confirm...",0
Text_Mev3_Query:	DC.B	"Mev3.0 : Query...",0
Text_Mev3_Inform:	DC.B	"Mev3.0 : Information...",0

_SystemName:		DC.B	"system.font",0
_DpaintName:		DC.B	"dpaint.font",0
_DosName:		DC.B	"dos.library",0
_IntuitionName:		DC.B	"intuition.library",0
_GraphicsName:		DC.B	"graphics.library",0
_GadToolsName:		DC.B	"gadtools.library",0
_AslName:		DC.B	"asl.library",0
_DiskFontName:		DC.B	"diskfont.library",0
    CNOP    0,2


 EVEN

File_Window_TagList:
Project0WindowTags:
File_Window_Screen:	;DC.L	WA_CustomScreen,0
			DC.L    WA_PubScreen,0
File_Window_Gadgets:	DC.L	WA_Gadgets,0
			DC.L    WA_Left,0
			DC.L    WA_Top,11
			DC.L    WA_Width,640
			DC.L    WA_Height,200-11
			DC.L    WA_IDCMP,LISTVIEWIDCMP!STRINGIDCMP!IDCMP_CLOSEWINDOW!IDCMP_REFRESHWINDOW
			DC.L    WA_Flags,WFLG_SIZEGADGET!WFLG_DRAGBAR!WFLG_DEPTHGADGET!WFLG_CLOSEGADGET!WFLG_SMART_REFRESH
			DC.L    WA_Title,Text_Mev3_Title
			DC.L    WA_ScreenTitle,Text_Mev3_Inform
			DC.L    WA_MinWidth,67
			DC.L    WA_MinHeight,21
			DC.L    WA_MaxWidth,640
			DC.L    WA_MaxHeight,256
			DC.L    TAG_DONE

;File_Screen_TagList:
;		DC.L	SA_Width,640
;		DC.L	SA_Height,200
;		DC.L	SA_Depth,3
;		DC.L	SA_DisplayID,HIRES_KEY
;		DC.L	SA_Title,Text_Mev3_Title
;		DC.L	SA_AutoScroll,TRUE
;;		DC.L	SA_Pens,Screen_DriPens
;;		DC.L    SA_Colors,Screen_Colours
;		DC.L	SA_Pens,Minus_1
;		DC.L	TAG_DONE

;File_Window_TagList:
;File_Window_Screen:	DC.L	WA_CustomScreen,0
;File_Window_Gadgets:	DC.L	WA_Gadgets,0
;;			DC.L	WA_Title,_DosName
;			DC.L	WA_Left,0
;			DC.L	WA_Top,11
;			DC.L	WA_Width,640
;			DC.L	WA_Height,200-11
;;			DC.L	WA_BackFill,0	
;			DC.L    WA_AutoAdjust,1
;			DC.L    WA_IDCMP,CYCLEIDCMP!BUTTONIDCMP!SLIDERIDCMP!TEXTIDCMP!IDCMP_INTUITICKS!IDCMP_MOUSEBUTTONS!IDCMP_DISKINSERTED!IDCMP_DISKREMOVED!IDCMP_VANILLAKEY!IDCMP_REFRESHWINDOW!LISTVIEWIDCMP
;			DC.L    WA_Flags,WFLG_SMART_REFRESH|WFLG_BACKDROP|WFLG_ACTIVATE
;
;			DC.L	TAG_DONE

File_Gadget_List:
		NewGadget	LISTVIEW_KIND,Gadget_ListView1_Tags,200,24,266,48,NULL,NULL,LISTVIEW_ID_TYPE,PLACETEXT_IN,NULL,NULL
		DC.L		-1

Gadget_ListView1_Tags:
		DC.L	GTLV_Labels,lvh
		DC.L    GTLV_ShowSelected,0
		DC.L	TAG_DONE
 EVEN

lvh:
ListviewList:
    DC.L    ListviewNodes0,0,ListviewNodes2

ListviewNodes0:
    DC.L    ListviewNodes1
    DC.L    ListviewList
    DC.B    0,0
    DC.L    _DiskFontName

ListviewNodes1:
    DC.L    ListviewNodes2
    DC.L    ListviewNodes0
    DC.B    0,0
    DC.L    Text_Mev3_Title

ListviewNodes2:
    DC.L    ListviewList+4
    DC.L    ListviewNodes1
    DC.B    0,0
    DC.L    Text_Mev3_Title

 ENDC

